feature: Add Organization Overview repository filter CY-5623
codacy/docs pull request #1048
Opened 2022-02-16 10:52 UTC by prcr

2022-02-16 17:30 UTC, inesgomas approved these changes

2022-02-17 11:21 UTC, alerizzo approved these changes

2022-03-15 14:46 UTC, inesgomas approved these changes

2022-07-22 13:28 UTC, alerizzo reviewed
Minor detail: docs/organizations/images/organization-overview-overall-quality-grouped.png shows the beta pill (which is no longer visible)

2022-07-27 15:39 UTC, inesgomas approved these changes

2022-08-23 15:12 UTC, alerizzo approved these changes

2022-08-23 15:26 UTC, inesgomas requested changes
We did some updated in the dropdown, so a new screenshot will be needed there. (some colors changed, and "select all" copy too)

2022-08-23 16:02 UTC, prcr commented
> We did some updated in the dropdown, so a new screenshot will be needed there. (some colors changed, and "select all" copy too)

Thanks, @inesgomas! I had noticed a small change but I was missing a "hard refresh" before I could see all the latest changes. :sweat_smile: It should reflect the latest version now.

2022-08-23 16:05 UTC, inesgomas approved these changes

2022-08-24 11:03 UTC, merged