docs: add markdownlint as a supported tool CY-4001
codacy/docs pull request #691
Opened 2021-05-27 16:30 UTC by pedrocodacy

Added as supported tool in
	- getting-started/supported-languages-and-tools
	- related-tools/codacy-plugin-tools
Added as tool with fix suggestions enabled in repositories-configure/github-integration#suggest-fixes

- [ ] wait for CY-3953 to be finished before merging

2021-05-27 16:31 UTC, pedrocodacy reviewed
Wait for CY-3953 to be finished before merging

2021-05-28 07:29 UTC, prcr requested changes
The maintainers of the tool aren't very consistent with the way they capitalize the name of the tool, but [most of the time they use all lowercase](https://github.com/markdownlint/markdownlint), so I would consider the official name of the tool to be **markdownlint**.

We also need to add the name of the tool to the file `.github/styles/Vocab/Codacy/accept.txt` so that the spellchecking step of the CI doesn't fail. :nerd_face:

2021-05-28 07:29 UTC, prcr commented on docs/getting-started/supported-languages-and-tools.md
>        <td><a href="https://github.com/remarkjs/remark-lint">RemarkLint</a></td>
The new tool is missing in the column "Static analysis":

```suggestion
      <td><a href="https://github.com/remarkjs/remark-lint">RemarkLint</a>, <a href="https://github.com/markdownlint/markdownlint">markdownlint</a></td>
```

2021-05-28 07:29 UTC, prcr commented on docs/getting-started/supported-languages-and-tools.md
> +      <td><a href="https://github.com/markdownlint/markdownlint">MarkdownLint</a></td>
Add the missing "wrench icon" with a link to an explanation of the suggested fixes feature:

![image](https://user-images.githubusercontent.com/60105800/119945355-3b3bc980-bf8d-11eb-9411-b6315e6c69e9.png)

```suggestion
      <td><a href="https://github.com/markdownlint/markdownlint">markdownlint</a>   <a href="#suggested-fixes">🔧</a></td>
```

2021-05-28 07:29 UTC, prcr commented on docs/related-tools/codacy-plugin-tools.md
> +<td><a href="https://github.com/remarkjs/remark-lint">MarkdownLint</a></td>
The name of the tools and our corresponding repositories are mixed up:

![image](https://user-images.githubusercontent.com/60105800/119946142-375c7700-bf8e-11eb-91aa-e3fb2414e0c4.png)

```suggestion
<td><a href="https://github.com/markdownlint/markdownlint">markdownlint</a></td>
<td><a href="https://github.com/codacy/codacy-markdownlint" class="skip-vale">codacy/codacy-markdownlint</a></td>
</tr>
<tr>
<td><a href="https://github.com/remarkjs/remark-lint">RemarkLint</a></td>
```

2021-05-28 07:29 UTC, prcr commented on docs/repositories-configure/integrations/github-integration.md
> +    -   The only two tools that suggests fixes are [ESLint](https://eslint.org/docs/rules/) and [MarkdownLint](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md). However, we're
Fix small typo:

```suggestion
    -   The only two tools that suggest fixes are [ESLint](https://eslint.org/docs/rules/) and [MarkdownLint](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md). However, we're planning to support suggestions from more tools.
```

2021-06-01 08:59 UTC, prcr approved these changes

2021-06-01 09:15 UTC, prcr submitted a review, later dismissed

2021-06-08 08:09 UTC, franciscodua approved these changes

2021-06-08 09:03 UTC, prcr commented on docs/repositories-configure/integrations/github-integration.md
> +    -   The only two tools that suggest fixes are [ESLint](https://eslint.org/docs/rules/) and [MarkdownLint](https://github.com/DavidAnson/markdownlint/blob/master/docs/RULES.md). However, we're pla
Correct capitalization of markdownlint and fix link for rules reference:

```suggestion
    -   The only two tools that suggest fixes are [ESLint](https://eslint.org/docs/rules/) and [markdownlint](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md). However, we're planning to support suggestions from more tools.
```

2021-06-08 09:24 UTC, prcr requested changes

2021-06-08 09:24 UTC, prcr commented on docs/getting-started/supported-languages-and-tools.md
>        <td><a href="https://github.com/remarkjs/remark-lint">RemarkLint</a></td>
The tool is missing under the column **Static Analysis**:

```suggestion
      <td><a href="https://github.com/remarkjs/remark-lint">RemarkLint</a>, <a href="https://github.com/DavidAnson/markdownlint">markdownlint</a></td>
```

2021-06-08 13:51 UTC, franciscodua commented
@prcr I just accepted your suggestions. Ready for another review 😄

2021-06-08 13:51 UTC, prcr approved these changes
:shipit: :tada:

2021-06-08 13:53 UTC, merged